#!/usr/bin/env python3

import sys
import gi
import pathlib
project_root = pathlib.Path.home() / '.TacOS_Stuff/TacOS_Settings_App'
sys.path.insert(0, str(project_root))
from pages.General_Settings import GeneralSettingsPage
from pages.Audio_Settings import AudioSettingsPage
from pages.Network_Settings import NetworkSettingsPage
from pages.Display_Settings import DisplaySettingsPage
from pages.Other_Settings import OtherSettingsPage
import os

script_dir = os.path.dirname(os.path.abspath(__file__))

gi.require_version("Gtk", "3.0")
gi.require_version("GdkPixbuf", "2.0")
from gi.repository import Gtk, Gdk, GdkPixbuf


css_provider = Gtk.CssProvider()
css_provider.load_from_path(f"{project_root}/style.css")

screen = Gdk.Screen.get_default()
style_context = Gtk.StyleContext()
style_context.add_provider_for_screen(
    screen,
    css_provider,
    Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION
)

class MainWindow(Gtk.Window):
    def __init__(self):
        super().__init__(title="TacOS Settings")
        self.set_default_size(600, 400)

        self.css_provider1 = Gtk.CssProvider()
        self.css_provider1.load_from_path(f"{project_root}/style.css")

        self.css_provider2 = Gtk.CssProvider()
        self.css_provider2.load_from_path(f"{project_root}/style2.css")

        screen = Gdk.Screen.get_default()
        style_context = Gtk.StyleContext()

        style_context.add_provider_for_screen(
            screen,
            self.css_provider1,
            Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION
        )
        self.current_theme = self.css_provider1

        #self.theme_button = Gtk.Button(label="Switch theme")
        #self.theme_button.connect("clicked", self.switch_theme)

        self.main_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        self.main_box.get_style_context().add_class("main_box")
        self.top_bar_box = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL)
        self.top_bar_box.get_style_context().add_class("top_bar")
        self.big_box = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL)
        self.big_box.get_style_context().add_class("bigbox")
        self.big_box.set_halign(Gtk.Align.START)

        self.box_1 = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        self.box_1.get_style_context().add_class("box_1")
        self.box_2 = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)

        self.top_bar_label = Gtk.Label(label="TacOS Settings")
        self.top_bar_close_button = Gtk.Button(label="")
        self.top_bar_close_button.connect("clicked", self.close_button_on_clicked)
        self.top_bar_close_button.get_style_context().add_class("close_button")

        self.about_page_button = Gtk.Button(label="About")
        self.about_page_button.get_style_context().add_class("about_dialog_button")
        self.about_page_button.connect("clicked", self.show_about_dialog)
        
        self.general_settings_page = GeneralSettingsPage(main_window=self)
        self.audio_settings_page = AudioSettingsPage()
        self.network_settings_page = NetworkSettingsPage()
        self.display_settings_page = DisplaySettingsPage()
        self.other_settings_page = OtherSettingsPage()

        self.stack = Gtk.Stack()
        self.stack.set_transition_type(Gtk.StackTransitionType.CROSSFADE)
        self.stack.set_transition_duration(500)
        self.stack.add_titled(self.general_settings_page, "General_Settings", "General Settings")
        self.stack.add_titled(self.audio_settings_page, "Audo_Settings", "Audio Settings")
        self.stack.add_titled(self.network_settings_page, "Network_Settings", "Network Settings")
        self.stack.add_titled(self.display_settings_page, "Display_Settings", "Display Settings")
        self.stack.add_titled(self.other_settings_page, "Other_Settings", "Other Settings")
        self.switcher = Gtk.StackSidebar()
        self.switcher.set_stack(self.stack)
        self.switcher.get_style_context().add_class("switcher")

        self.box_1.pack_start(self.switcher, True, True, 0)
        self.box_2.add(self.stack)
        self.top_bar_box.pack_start(self.about_page_button, False, False, 0)
        self.top_bar_box.set_center_widget(self.top_bar_label)
        self.top_bar_box.pack_end(self.top_bar_close_button, False, False, 0)

        self.big_box.add(self.box_1)
        self.big_box.add(self.box_2)

        self.main_box.add(self.top_bar_box)
        self.main_box.add(self.big_box)
        #self.main_box.add(self.theme_button)
        self.add(self.main_box)

    def switch_to_theme_1(self, widget):
        screen = Gdk.Screen.get_default()
        style_context = Gtk.StyleContext()

        style_context.remove_provider_for_screen(
            screen,
            self.current_theme
        )

        self.current_theme = self.css_provider1

        style_context.add_provider_for_screen(
            screen,
            self.current_theme,
            Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION
        )

    def switch_to_theme_2(self, widget):
        screen = Gdk.Screen.get_default()
        style_context = Gtk.StyleContext()

        style_context.remove_provider_for_screen(
            screen,
            self.current_theme
        )

        self.current_theme = self.css_provider2

        style_context.add_provider_for_screen(
            screen,
            self.current_theme,
            Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION
        )

    def show_about_dialog(self, widget):
        about_dialog = Gtk.AboutDialog()
        about_dialog.set_program_name("TacOS Settings")
        about_dialog.set_version("version: 0.01")
        about_dialog.set_comments("This is a settings app for TacOS, a Linux distro\nbased on Arch linux that I made as part\nof a coding challenge called Siege.")
        about_dialog.set_website("https://github.com/bunnybunnybun/TacOS")
        about_dialog.set_title("About TacOS Settings")
        pixbuf = GdkPixbuf.Pixbuf.new_from_file("/home/carlisle/.TacOS_Stuff/assets/waybar/white_settings_icon_normal.png")
        about_dialog.set_logo(pixbuf)
        about_dialog.set_authors(["Pixelated Carlito"])
        about_dialog.set_transient_for(self)
        about_dialog.run()
        about_dialog.destroy()

    def close_button_on_clicked(self, widget):
        win.destroy()

win = MainWindow()
win.connect("destroy", Gtk.main_quit)
win.show_all()
Gtk.main()